title: Marwan Kambriss
# logo: hot link l sura hon
description: >
  ğŸ“ˆ Welcome to my GitHub portfolio! ğŸ“Š

  I'm Marwan Kambriss, a data scientist and financial analyst with a unique blend of expertise in data science and finance. With a double major in both disciplines, I bring a comprehensive understanding of financial markets and the power of data-driven insights to drive informed decision-making.
  <br><br>

  ğŸ“ I hold dual degrees in Data Science and Finance, giving me a strong foundation in both the quantitative aspects of finance and the technical skills required to extract meaningful insights from data. My educational journey has equipped me with the knowledge and tools needed to excel in the dynamic world of finance and data analytics.

  ğŸ§‘â€ğŸ’¼ I'm passionate about leveraging data to enhance financial analysis, optimize investment strategies, and uncover hidden opportunities. My mission is to bridge the gap between traditional financial analysis and cutting-edge data science techniques to deliver actionable results.
  <br><br>
  <a href="https://www.linkedin.com/in/marwan-kambriss/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
