title: Marwan Kambriss
# logo: hot link l sura hon
description: >
  ğŸ“ˆ Welcome to my GitHub portfolio! ğŸ“Š
  <br><br>
  I'm Marwan Kambriss, a data scientist and financial analyst with a unique blend of expertise in data science and finance. With a double major in both disciplines, I bring a comprehensive understanding of financial markets and the power of data-driven insights to drive informed decision-making.
  <br><br>

  ğŸ“ With dual degrees in Data Science and Finance, I possess a versatile skill set for diverse domains. ğŸŒ My educational journey equips me to excel in both finance and various other fields, leveraging data to drive innovation and actionable insights.

  ğŸ§‘â€ğŸ’¼ Passionate about harnessing data's power to transform industries beyond finance, I'm eager to explore new challenges and opportunities. ğŸš€ My mission is to apply data science techniques to drive growth and success across diverse domains. ğŸ’¡
  <br><br>
  <a href="https://www.linkedin.com/in/marwan-kambriss/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
