title: Marwan Kambriss
# logo: hot link l sura hon
description: >
  ğŸ“ˆ Welcome to my GitHub portfolio! ğŸ“Š
  <br><br>
  I'm Marwan Kambriss, a data scientist and financial analyst with a unique blend of expertise in data science and finance. With a double major in both disciplines, I bring a comprehensive understanding of financial markets and the power of data-driven insights to drive informed decision-making.
  <br><br>
  ğŸ“ Dual degrees in Data Science and Finance ğŸ“ˆ + ğŸ“Š = ğŸ” Equipped for dynamic opportunities in finance and beyond.
  <br>
  ğŸ§‘â€ğŸ’¼ Passionate about data-driven insights, optimizing financial strategies, and uncovering opportunities across industries. ğŸš€ Bridging data science skills to deliver results wherever they are needed. ğŸ’¡
  <br>
  <a href="https://www.linkedin.com/in/marwan-kambriss/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
